server:
  port: 9000

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ev-carpooling
        registration:
          keycloak:
            provider: keycloak
            client-id: ev-gateway
            authorization-grant-type: password
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates: [Path=/api/users/**]
          filters: [TokenRelay=]
        - id: ride-service
          uri: lb://ride-service
          predicates: [Path=/api/rides/**]
          filters: [TokenRelay=]
        - id: booking-service
          uri: lb://booking-service
          predicates: [Path=/api/bookings/**]
          filters:
            - TokenRelay