version: '3.8'
services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports: ["8761:8761"]
    networks: [ev-network]
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5

networks:
  ev-network:
    external: true